=== the-singing-mountain/Web-Technologies-Lab/Lab 7/XSLT/lab6note.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT chess_pieces (heading, piece+)>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT piece (name, value, description)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT value_name (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT description (#PCDATA)>

=== the-singing-mountain/Web-Technologies-Lab/Lab 7/XSL-FO/lab6.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="lab7.xsl" ?>
<!DOCTYPE chess_pieces SYSTEM "lab6note.dtd">
<chess_pieces>
<heading>Chess Piece Details</heading>
<piece>
<name>King</name>
<value>Value: maximum</value>
<description>The most important piece on the board.The king controls 8 squares on the board from the centre. It can move like a Queen, i.e., horizontally, vertically and diagonally, but can only move one square.</description>
</piece>

<piece>
<name>Queen</name>
<value>Value: 9</value>
<description>The queen controls 27 squares on the board from the centre. It is the strongest piece on the board. It can move both like a bishop, and like a rook, i.e., it can move horizontally, vertically and diagonally.</description>
</piece>

<piece>
<name>Rook</name>
<value>Value: 5</value>
<description>The Rook controls 14 squares on the board from the centre. It can only move horizontally and vertically.</description>
</piece>

<piece>
<name>Bishop</name>
<value>Value: 3</value>
<description>Bishop controls 13 squares on the board from the centre. Each bishop can only move on the diagonals of the same colour it was initially on the board.</description>
</piece>

<piece>
<name>Knight</name>
<value>Value: 3</value>
<description>Knight controls 8 squares on the board from the centre. Each knight can move in an L shape, 3 squares away. A knight can only move on alternating colours.</description>
</piece>
</chess_pieces>
